<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{0426f05b-5f97-0ad4-3f3a-5f3fc39bb59b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	eventEmitter_TestSuit : EventEmitter_TestSuit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>