<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MockEvent" Id="{2f9c554a-2034-412e-9e68-a68075e23a21}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MockEvent IMPLEMENTS I_Event
VAR
	_name : T_MAXSTRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>