<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EventHandlerItemOnceOnly" Id="{fe48e8b4-7ae4-4438-9da4-8ee2563092e3}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK EventHandlerItemOnceOnly EXTENDS EventHandlerItem
VAR
	parent : I_EventEmitter;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{842a482e-a238-4285-af46-d80720fa60ac}" />
    <Method Name="Emit" Id="{17f8c72e-1b12-4a24-bf07-283947ac7690}">
      <Declaration><![CDATA[METHOD PUBLIC Emit
VAR_INPUT
	EventName : T_MaxString;
	Event : I_Event;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Emit(EventName,Event);
parent.OffEvent(name,handler);]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{81d52a11-588d-4036-aaac-a9abca8bf4fe}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	Name : T_MAXSTRING;
	Handler : I_EventHandler;
	Parent : I_EventEmitter;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.parent := Parent;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>